version: "3.9"
services:
  productos-service:
    build:
      context: ./Backend/productos-service
    container_name: productos-service
    ports:
      - "8081:8081"

  inventario-service:
    build:
      context: ./Backend/inventario-service
    container_name: inventario-service
    ports:
      - "8082:8082"
    environment:
      - PRODUCT_SERVICE_URL=http://productos-service:8081/product-microservice/products/
    depends_on:
      - productos-service

  api-gateway:
    build:
      context: ./nginx
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - productos-service
      - inventario-service

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "4200:4000"
    depends_on:
      - api-gateway