-- Inventario inicial
INSERT INTO INVENTORIES (ID, PRODUCT_ID, QUANTITY) VALUES (1, 1, 50);
INSERT INTO INVENTORIES (ID, PRODUCT_ID, QUANTITY) VALUES (2, 2, 30);
INSERT INTO INVENTORIES (ID, PRODUCT_ID, QUANTITY) VALUES (3, 3, 20);
